### ISSUE TITLE
Using a mapped state function, the initial 'value' isn't converted to immutable

### ISSUE THREAD

**Issue by idream3** [christianalfoni/immutable-store#14]
If you try to use this value in your view you get an error because `toJS()` method doesn't exist, so you have to check for it. 

```javascript
function mapState() {
  return {
    value: someValue,  // not converted to immutable initially
    deps: { ... },
    get(value, deps) { ... }
  }
}
```

**Comment by christianalfoni** [comment]
Okay, this was a bit harder than I thought. Have to do some refactoring... but will fix it ;-)

**Comment by christianalfoni** [comment]
Okay, this should be fixed now :-)
