### ISSUE TITLE
Missing .set()?

### ISSUE THREAD

**Issue by jrust** [christianalfoni/immutable-store#2]
I'm trying to create a state object that has strings as values, but I can't find a way to change them.  Freezer appears to have `.set` but I haven't seen anything like that in immutable-store.  Another use for `.set` would be replacement of an array (e.g. `store.set(items, [1,2,3])`) which is what I want to do when I get a new list of items back from the server.

Thanks!

**Comment by christianalfoni** [comment]
Hi there @jrust ,

immutable-store does have a set method, but not on the store itself:

```javascript
var store = Store({
  foo: {}
});
store.set() // fails
store.foo.set('foo', 'bar'); // works
```

I am looking into a way to fix this :-)

**Comment by christianalfoni** [comment]
Okay, released new version, should be okay now :-)

**Comment by jrust** [comment]
Works great, thanks!
