### ISSUE TITLE
Pushing an element changes subsequent operations

### ISSUE THREAD

**Issue by jrust** [christianalfoni/immutable-store#4]
If I push an element onto an array and then do a `set` afterwards it changes the array, not the top-level store:
```
var state = Store({ items: [] });
state = state.items.push({id: 1});
state = state.set('foo', 'bar');
console.log(state.foo); // undefined
console.log(state.items[0].foo); // bar
```

**Comment by christianalfoni** [comment]
I am working on this now, found the bug, will release another version a bit later :-) Thanks a lot for testing this!

**Comment by christianalfoni** [comment]
Okay, pushed another version. Thanks again!
